spring:
  config.activate.on-profile: insertbatch
  datasource:
    url:  jdbc:h2:tcp://localhost/~/batchinsert
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        format_sql: true
#        show_sql: true
        jdbc:
          batch_size: 1000
    open-in-view: false
logging:
  level:
    org.hibernate.SQL: info
