spring:
  config:
    import: application-insertbatch.yml, application-lock.yml, application-optimisticlock.yml
  profiles:
    active: lo
    group:
      ib: insertbatch
      lo: lock
      op: oplock